import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
const Sidebar = dynamic(() => import("@/components/ui/sidebar"), {
  ssr: false,
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen w-full bg-white text-black flex",
          inter.className
          // { "debug-screens": process.env.NODE_ENV === "development" }
        )}
      >
        {/* Sidebar */}
        <div className="hidden md:block">
          <Sidebar />
        </div>
        {/* main page */}
        <div className="p-8 w-full">{children}</div>
      </body>
    </html>
  );
}
